import type { Metadata } from "next";
import "@/styles/index.css";
import Sidebar from '@/components/Sidebar';
import { geistMono, geistSans } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next React Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container">
          <div className="main">
            <Sidebar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
